# Generated by Django 4.0.1 on 2022-02-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pic',
            field=models.ImageField(upload_to='static/images/user_images/portfolio.png'),
        ),
    ]
