# Generated by Django 4.0.1 on 2022-02-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hours',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Seasonal', 'Seasonal')], default='Full Time', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='job_categories',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Other', 'Other'), ('Accounting ', 'Accounting'), ('Aviation / Aerospace', 'Aviation / Aerospace'), ('Engineering', 'Engineering'), ('Child Care', 'Child Care'), ('Clerical / Office', 'Clerical / Office'), ('Communications', 'Communications'), ('Construction', 'Construction'), ('Computer / Software Enginner', 'Computer / Software Engineer'), ('Customer Service', 'Customer Service'), ('Education / Teaching', 'Education /Education'), ('Federal / State / Civil Government', 'Federal / State / Civil Government'), ('Helthcare / Medical', 'Healthcare / Medical'), ('Human Resources', 'Human Resources'), ('Legal', 'Legal'), ('Management', 'Management'), ('Mechanic', 'Mechanic'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Social Work', 'Social Work'), ('Real Estate', 'Real estate'), ('Transportation', 'Transportation'), ('Work From Home', 'Work From Home'), ('Other', 'Other'), ('N/A', 'N/A')], default='N/A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='job_description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='job_title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='remote_type',
            field=models.CharField(choices=[('Remote "Yes"', 'Remote "Yes"'), ('Remote "No"', 'Remote "No"'), ('Open "Yes or No"', 'Open "Yes or No"'), ('Partial Remote', 'Partial Remote'), ('No Preference', 'No Preference')], default='No Preference', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='skills',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='job_summary',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
