# Generated by Django 4.0.1 on 2022-02-17 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_remove_message_text_message_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='post_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='post_app.post'),
        ),
    ]
